apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: kpr-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-data
  namespace: kpr-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plots-data
  namespace: kpr-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
