apiVersion: v1
kind: Service
metadata:
  name: kpr-web
  namespace: kpr-analytics
  labels:
    app: kpr-web
spec:
  type: NodePort
  selector:
    app: kpr-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
