name: "Self-Hosted CI Test"

on:
  workflow_dispatch: 

jobs:
  local-run:
    runs-on: self-hosted 

    steps:
      - name: "Downloading code"
        uses: actions/checkout@v4

      - name: "Installing dependencies"
        run: |
          python3 -m pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: "Running data_quality module"
        run: |
          cd src
          python3 data_load.py
          python3 data_quality.py

      - name: "Uploading Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: local-results
          path: data/processed/
